### PR TITLE
Brian Carlson - FP3

### PR DESCRIPTION
**Pull request by carlsonb99**

### CODE REVIEW

**Comment by marksherman** [comment]
@norman2005 is missing FP2, I cannot proceed until that pull request is seen and resolved.

**Comment by marksherman** [comment]
I'm assuming @carlsonb99 closed this by accident (effectively withdrawing the submission), so I am re-opening. I need to see it to make the group.

A submission should remain open until I close it. You can make updates to the branch, and it will be immediately reflected without the need to recreate the pull request. Just leave a comment telling me you made updates and I will look at it.

**Comment by marksherman** [comment]
Team has been created.

**Comment by carlsonb99** [comment]
So we were confused, since we didn't realize Josh and I both submitted this. On Josh's submission it said these were duplicates along with norman2005's missing FP2 question. Norm said/shows that he submitted FP2 and Josh's submission was closed. I assumed you accepted his so I closed mine under the assumption of the duplicate. 

Sorry about that.

**Comment by marksherman** [comment]
the one marked as duplicate was closed because I deemed it to be the copy (later submission), and this one was the original I was keeping open until we resolved norman's FP2. 

I talked to Norman this morning, and he should have that submitted any time now. There's nothing currently in the way.

**Comment by carlsonb99** [comment]
Ok great

Thanks

**Comment by marksherman** [comment]
all set!

**Pull request closed without merging**
