### PR TITLE
submission Jose Flores

### PR DESCRIPTION
**Pull request by josefflores**

### CODE REVIEW

**Comment by marksherman** [comment]
Cool idea. Exciting.

Munkhjargal, you still have not submitted FP1, and I can't grade anything past it until you do.

**Comment by marksherman** [comment]
Do you want me to make you a github team under the class organization? That's what I'm offering to all teams.

**Comment by marksherman** [comment]
I've created a team for you. If you want a better team name, I can edit it. Maybe you can, too. Not sure.

You may now proceed with the project.

@umasslowellmj has not submitted satisfactory FP1 or FP2 and is therefore missing those grades. MJ, if you'd like to expand those submissions and notify me, I'll gladly give you grades for them.

**Comment by umasslowellmj** [comment]
@marksherman Thank you very much. I will submit a remake.

**Pull request closed without merging**
